apiVersion: v1
kind: Service
metadata:
  name: redis-cache
  namespace: dev
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    name: redis-cache
    system: url-shortening-system
    app: redis
    type: cache
  ports:
    - name: redis-cache
      port: 6379
      targetPort: 6379
      protocol: TCP