apiVersion: v1
kind: Service
metadata:
  name: original-link-database-headless
spec:
  clusterIP: None
  selector:
    system: url-shortening-system
    app: original-link-database
  ports:
    - port: 5432
      targetPort: 5432
      name: original-link-database