apiVersion: v1
kind: Service
metadata:
  name: original-link-database
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30056
  selector:
    name: postgres
    system: url-shortening-system
    app: original-link-database
    type: database
    role: replica