apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: short-link-database-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: short-link-database-storage
  local:
    path: /local/pgmaster/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists


