apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: short-link-database-data-pvc
  namespace: dev
spec:
  storageClassName: short-link-database-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi