apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: short-link-database
  namespace: dev
spec:
  selector:
    matchLabels:
      name: postgres
      system: url-shortening-system
      app: short-link-database
      type: database
      role: master
  serviceName: short-link-database
  template:
    metadata:
      labels:
        name: postgres
        system: url-shortening-system
        app: short-link-database
        type: database
        role: master
    spec:
      automountServiceAccountToken: false
      containers:
        - name: short-link-database-exporter
          image: prometheuscommunity/postgres-exporter:v0.18.1
          imagePullPolicy: IfNotPresent
          env:
            - name: DATA_SOURCE_URI
              value: short-link-database:5432/link_db?sslmode=disable
            - name: DATA_SOURCE_USER
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: POSTGRES_USER
            - name: DATA_SOURCE_PASS
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 9187
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
              ephemeral-storage: 256Mi
            limits:
              memory: 256Mi
              cpu: 250m
              ephemeral-storage: 256Mi

        - name: short-link-database
          image: postgres:17
          imagePullPolicy: IfNotPresent
          args:
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
              ephemeral-storage: 1Gi
            limits:
              memory: 1Gi
              cpu: 350m
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: short-link-database-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-config
              mountPath: /etc/postgresql/postgresql.conf
              subPath: postgresql.conf
            - name: short-link-database-master-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: postgres-config
          configMap:
            name: postgres-config
            defaultMode: 0644
        - name: short-link-database-master-init
          configMap:
            name: short-link-database-master-init
            defaultMode: 0644
        - name: short-link-database-data
          persistentVolumeClaim:
            claimName: short-link-database-data-pvc