apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: dev
  name: grafana-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: grafana-storage
  local:
    path: /local/grafana/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists