apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  name: grafana
  labels:
    name: grafana
    system: url-shortening-system
    type: monitoring
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      name: grafana
      system: url-shortening-system
      type: monitoring
  template:
    metadata:
      namespace: dev
      name: grafana
      labels:
        name: grafana
        system: url-shortening-system
        type: monitoring
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: grafana
          image: grafana/grafana:12.4.0-20836657505
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_METRICS_ENABLED
              value: "true"
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: GRAFANA_ADMIN_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-shortening-system-secrets
                  key: GRAFANA_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
              ephemeral-storage: 1Gi
            limits:
              cpu: 250m
              memory: 750Mi
              ephemeral-storage: 1Gi
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            failureThreshold: 60
            timeoutSeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 20
            successThreshold: 1
          volumeMounts:
            - mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              subPath: datasources.yml
              name: config-volume
            - mountPath: /var/lib/grafana
              name: grafana-pv
      volumes:
        - name: config-volume
          configMap:
            name: grafana-config
        - name: grafana-pv
          persistentVolumeClaim:
            claimName: grafana-pvc