apiVersion: v1
kind: Service
metadata:
  name: short-link-creation-service
  namespace: dev
spec:
  selector:
    name: short-link-creation-service
    system: url-shortening-system
    type: application
  type: ClusterIP
  ports:
    - name: http
      port: 8087
      targetPort: 8087
      protocol: TCP